Orion/runbooks 1
OctopusDeploy/cli pull request #104
Opened 2022-10-03 04:20 UTC by borland

2022-10-04 00:10 UTC, borland commented on pkg/cmd/release/deploy/deploy.go
> +func ScheduledStartTimeAnswerFormatter(datePicker *surveyext.DatePicker, t time.Time) string {
this (along with various other things in this file) is now public so that `runbook run` can re-use it

2022-10-05 00:16 UTC, domenicsim1 reviewed
Overall, looks good to me 👍  Just a some commented out code that can be removed.
Leaving unapproved so @slewis74 can can review.

2022-10-05 00:16 UTC, domenicsim1 commented on pkg/cmd/runbook/run/run.go
> +		//}
remove this

2022-10-05 01:01 UTC, slewis74 requested changes
Tenanted vs Untenanted isn't a thing for runbooks. I think we should have a package, e.g. `execution`, for the shared code between deployments and runbook runs

2022-10-05 02:11 UTC, borland commented on pkg/cmd/runbook/run/run.go
> +		//}
:+1

2022-10-05 02:14 UTC, borland commented on pkg/cmd/runbook/run/run.go
> +	// this is what the portal does. Can we do it better? I don't know
👍

2022-10-05 02:16 UTC, borland commented on pkg/cmd/runbook/run/run.go
> +// This mirrors determineIsTenanted in deploy release, but looks at a runbook, rather than a project
I don't understand why we should remove `determineIsTenanted` here?

Like deployments, runbooks can either be in the "Yes / No / Either" state, at least that's how the portal seems to work?

2022-10-05 02:20 UTC, borland commented on pkg/cmd/runbook/run/run.go
> +	// tenanted runs only allow one environment, untenanted allows multiple environments
I'm confused by this then.

The portal follows deployments, in that
- Tenanted runs only allow a single environment
- Nontenanted runs allow multiple environments.

Is the portal wrong?

2022-10-05 02:20 UTC, borland commented on pkg/executor/runbook.go
> +	"github.com/OctopusDeploy/go-octopusdeploy/v2/pkg/deployments"
Will do

2022-10-10 05:14 UTC, domenicsim1 reviewed
As discussed with @slewis74, tests will be revisited in future PR.

2022-10-10 05:26 UTC, slewis74 approved these changes

2022-10-10 06:02 UTC, merged