feat: worker listening-tentacle create
OctopusDeploy/cli pull request #145
Opened 2022-11-17 04:25 UTC by benPearce1

feat: worker ssh create

2022-11-18 00:46 UTC, jbristowe commented on pkg/cmd/worker/listening-tentacle/create/create.go
> +	fmt.Fprintf(opts.Out, "Successfully created listening tentcle worker '%s'.\n", worker.Name)
```suggestion
	fmt.Fprintf(opts.Out, "Successfully created Listening Tentacle worker '%s'.\n", worker.Name)
```

2022-11-18 00:47 UTC, jbristowe commented on pkg/cmd/worker/listening-tentacle/create/create.go
> +	flags.StringVar(&createFlags.URL.Value, createFlags.URL.Name, "", "The network address at which the Tentacle can be reached.")
```suggestion
	flags.StringVar(&createFlags.URL.Value, createFlags.URL.Name, "", "The network address at which the Listening Tentacle can be reached.")
```

2022-11-18 00:47 UTC, jbristowe commented on pkg/cmd/worker/listening-tentacle/create/create.go
> +			Help:    "The X509 certificate thumbprint that securely identifies the Tentacle.",
```suggestion
			Help:    "The X509 certificate thumbprint that securely identifies the Listening Tentacle.",
```

2022-11-18 00:47 UTC, jbristowe commented on pkg/cmd/worker/listening-tentacle/create/create.go
> +			Help:    "The network address at which the Tentacle can be reached.",
```suggestion
			Help:    "The network address at which the Listening Tentacle can be reached.",
```

2022-11-18 00:47 UTC, jbristowe commented on pkg/cmd/worker/listening-tentacle/listening-tentacle.go
> +		Short:   "Manage listening tentacle workers",
```suggestion
		Short:   "Manage Listening Tentacle workers",
```

2022-11-18 00:47 UTC, jbristowe commented on pkg/cmd/worker/listening-tentacle/listening-tentacle.go
> +		Long:    "Work with Octopus Deploy listening tentacle workers.",
```suggestion
		Long:    "Work with Listening Tentacle workers in Octopus Deploy.",
```

2022-11-18 00:48 UTC, jbristowe commented on pkg/cmd/worker/shared/workerpool.go
> +	cmd.Flags().StringSliceVar(&flags.WorkerPools.Value, flags.WorkerPools.Name, []string{}, "The worker pools which the worker will be a member of")
```suggestion
	cmd.Flags().StringSliceVar(&flags.WorkerPools.Value, flags.WorkerPools.Name, []string{}, "The pools of which the worker will be a member.")
```

2022-11-18 00:48 UTC, jbristowe commented on pkg/cmd/worker/shared/workerpool.go
> +		selectedPools, err := question.MultiSelectMap(opts.Ask, "Select the worker pools to assign the worker to", allWorkerPools, func(pool *workerpools.WorkerPoolListResult) string { return pool.Name },
```suggestion
		selectedPools, err := question.MultiSelectMap(opts.Ask, "Select the worker pools to assign to the worker.", allWorkerPools, func(pool *workerpools.WorkerPoolListResult) string { return pool.Name }, true)
```

2022-11-18 00:49 UTC, jbristowe commented on pkg/cmd/worker/shared/workerpool_test.go
> +		testutil.NewMultiSelectPrompt("Select the worker pools to assign the worker to", "", []string{"Groundskeeper", "Swim instructor"}, []string{"Groundskeeper", "Swim instructor"}),
```suggestion
		testutil.NewMultiSelectPrompt("Select the worker pools to assign to the worker", "", []string{"Groundskeeper", "Swim instructor"}, []string{"Groundskeeper", "Swim instructor"}),
```

2022-11-18 00:51 UTC, jbristowe commented on pkg/cmd/worker/shared/workerpool_test.go
> +		testutil.NewMultiSelectPrompt("Select the worker pools to assign the worker to", "", []string{"Groundskeeper", "Swim instructor"}, []string{"Groundskeeper", "Swim instructor"}),
```suggestion
		testutil.NewMultiSelectPrompt("Select the worker pools to assign to the worker", "", []string{"Groundskeeper", "Swim instructor"}, []string{"Groundskeeper", "Swim instructor"}),
```

2022-11-18 00:52 UTC, jbristowe commented on pkg/cmd/worker/ssh/ssh.go
> +		Long:    "Work with Octopus Deploy SSH workers.",
```suggestion
		Long:    "Work with SSH workers in Octopus Deploy.",
```

2022-11-18 00:52 UTC, jbristowe commented on pkg/cmd/worker/worker.go
> +		Long:  `Work with Octopus Deploy workers.`,
```suggestion
		Long:  `Work with workers in Octopus Deploy.`,
```

2022-11-18 00:52 UTC, jbristowe commented on pkg/cmd/worker/worker.go
> +			$ %s tenant ls
```suggestion
			$ %s worker ls
```

2022-11-18 00:53 UTC, jbristowe requested changes
Minor edits, otherwise LGTM.

2022-11-18 01:12 UTC, benPearce1 commented on pkg/cmd/worker/worker.go
> +			$ %s tenant ls
🤦

2022-11-18 02:40 UTC, jbristowe approved these changes

2022-11-18 03:33 UTC, merged

2022-11-21 01:03 UTC, benPearce1 commented
BEGIN_COMMIT_OVERRIDE
feat: worker listening-tentacle create
feat: worker ssh create
END_COMMIT_OVERRIDE