feat: worker view
OctopusDeploy/cli pull request #148
Opened 2022-11-18 04:59 UTC by benPearce1

[sc-29479]

![image](https://user-images.githubusercontent.com/5336529/202620660-2e8ae33e-39f1-4abd-8338-03d1a064314a.png)

2022-11-18 05:01 UTC, jbristowe commented on pkg/cmd/worker/listening-tentacle/view/view.go
> +			$ %s worker worker view Machines-100
```suggestion
			$ %s worker listening-tentacle view 'WindowsWorker'
			$ %s worker listening-tentacle view Machines-100
```

2022-11-18 05:02 UTC, jbristowe requested changes
Minor edits, otherwise LGTM

2022-11-18 05:26 UTC, jbristowe approved these changes

2022-11-18 05:36 UTC, merged

2022-11-21 01:01 UTC, benPearce1 commented
BEGIN_COMMIT_OVERRIDE
feat: worker view
feat: worker listening-tentacle view 
feat: worker polling-tentacle view
feat: worker ssh view
END_COMMIT_OVERRIDE