feat: accounts slugs
OctopusDeploy/cli pull request #87
Opened 2022-09-25 20:42 UTC by domenicsim1

2022-09-26 07:29 UTC, borland requested changes

2022-09-26 07:29 UTC, borland commented on pkg/cmd/account/aws/create/create_test.go
> +	opts.Space = spaceID
As above, trivial, but maybe nicer if these are assigned inside the `{ }` for CreateOptiosn

2022-09-26 07:29 UTC, borland commented on pkg/cmd/account/azure/create/create_test.go
> +	}).AnswerWith("d2486c05-0cac-4d54-a91e-654043036f33")
Tip: If you have some validation here (e.g. a validator that it's a GUID of the correct format) then it's very easy to throw a validation check into the middle of the test here.

```
q = qa.ExpectQuestion(t, &survey.Input { ... )

validationErr := q.AnswerWith("ddddd")
assert.EqualError(t, validationErr, "should be a guid format or something")

validationErr := q.AnswerWith("<proper guid>")
assert.Nil(t, validationErr)
```

2022-09-26 07:29 UTC, borland commented on pkg/cmd/account/ssh/create/create_test.go
> +func TestGCPAccountCreatePropmtMissing(t *testing.T) {
Prompt

2022-09-27 01:39 UTC, slewis74 commented on pkg/cmd/account/aws/list/list.go
> +				Slug      string
I'd assume it'll just display a blank, which I think is fine 👍

2022-09-27 01:44 UTC, slewis74 approved these changes
Overall looking 👍 

Per @borland 's comment, a few of the tests have `Propmt` in the name, rather than `Prompt`, which would be worth fixing.

2022-09-28 20:23 UTC, borland approved these changes

2022-09-29 02:29 UTC, merged